// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using System.Text.Json.Serialization;

namespace AngularProjectApi.Models;

[Table("District")]
public partial class District
{
    [Key]
    public int Number { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [JsonIgnore]
    public virtual ICollection<Village> Villages { get; set; } = new List<Village>();
}