// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using System.Text.Json.Serialization;

namespace AngularProjectApi.Models;

public partial class Village
{
    [Key]
    public int Number { get; set; }
    
    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Column("District_Number")]
    public int DistrictNumber { get; set; }

    [ForeignKey(nameof(DistrictNumber))]
    [JsonIgnore]
    public virtual District District { get; set; }
}